apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Release.Name}}-kibana-configmap
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kibana.labels" . | indent 4 }}
data:
  # Your env variables should be written here.
  ELASTICSEARCH_URL: "{{ .Values.elasticsearch.url }}"

